### PR TITLE
Revert to 3.0.23 and rerender

### PR DESCRIPTION
**Pull request by pmlandwehr**
Reverting the version and rerendering so that we can get a rerender of the last version of `celery`. (Ref. https://github.com/conda-forge/celery-feedstock/pull/7) for `py36`.

### CODE REVIEW

**Comment by jakirkham** [comment]
Instead of reverting it, could we try creating a branch for `3.3` and then you can try to he that to build for Python 3.6?

**Comment by jakirkham** [comment]
Have created the `v3.3` branch for this purpose. Please redirect this PR to that branch or close and open a new PR.

**Comment by pmlandwehr** [comment]
@jakirkham redirected! Can you merge this?

**Comment by jakirkham** [comment]
Could we please rebase out or squash the 3.5 related commits to clean this up a bit? If you are unsure of how to do this, I can try to take a look.

**Comment by pmlandwehr** [comment]
Gonna close this and restart it.

**Pull request closed without merging**
